---

logging:
  level:
    com:
      netflix:
        eureka:OFF
        discovery:OFF

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

  server:
    waitTimeInMsWhenSyncEmpty: 0
    enableSelfPreservation: false

security:
  user:
    name: Tleitzke
    password: Trl0853
