build_task: pipelines/gradle/tasks/gradle-assemble.yml # don't change
deploy_dev_task: pipelines/cf/tasks/blue-green-deploy.yml # don't change

app_name: eureka-server # don't change
jar_name: TLeitzke-eureka-server # set this to '<first_initial><lastname>-eureka-server' ex: sgreenberg-eureka-server

github_app_repo_uri: https://github.com/TLeitzke/Eureka-server.git # https url of your eureka-server app github fork.  ex: https://github.com/spgreenberg/eureka-server-initial.git
github_app_repo_branch: master # don't change

github_pipelines_repo_uri: https://github.com/TLeitzke/training-pipelines-initial.git # https url of your training-pipelines-initial fork.  ex: https://github.com/spgreenberg/training-pipelines-initial.git
github_pipelines_repo_branch: master # don't change

version_bucket: rscale-training-bucket # don't change
version_bucket_region_name: us-west-2 # don't change

version_key: TLeitzke-eureka-server-0.0.1 # set to '<first_initial><lastname>-eureka-server-version'.  ex: sgreenberg-eureka-server-version
initial_version: 0.0.1

artifact_regexp: TLeitzke-eureka-server-(.*).jar # set to '<first_initial><lastname>-eureka-server-(.*).jar'.  ex: sgreenberg-eureka-server-(.*).jar
artifact_bucket: rscale-training-bucket # don't change
artifact_bucket_region_name: us-west-2 # don't change

cf_dev_api: https://api.run.pivotal.io # set to cf api endpoint
cf_dev_organization: rscale-training-3 # set to your org
cf_dev_space: travis.leitzke@cgi.com # set to your space
cf_dev_hostname: eureka-server-TLeitzke # set to 'eureka-server-<first_initial><lastname>'. ex: eureka-server-sgreenberg
cf_dev_domain: cfapps.io # set to the apps domain for your CF
cf_dev_manifest: eureka_manifest.yml # set to the dev manifest path in your eureka-server app repository. ex: dev-manifest.yml
